// background.js
console.log("YouTube Summary: Background script loaded");

chrome.runtime.onInstalled.addListener(() => {
  console.log("YouTube Summary: Extension installed");
});

// Handle messages from content script
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  console.log("YouTube Summary: Message received in background:", request);

  if (request.action === "generateSummary") {
    generateAISummary(request)
      .then((summary) => {
        sendResponse({ summary });
      })
      .catch((error) => {
        console.error("YouTube Summary: Error generating summary:", error);
        sendResponse({ error: error.message });
      });
    return true; // Keep message channel open for async response
  }

  return true;
});

// Generate AI summary using OpenAI API
async function generateAISummary({ transcript, title, channel, url }) {
  try {
    // Get API key from storage
    const result = await chrome.storage.sync.get([
      "openaiApiKey",
      "customPrompt",
    ]);
    const apiKey = result.openaiApiKey;

    if (!apiKey) {
      throw new Error(
        "OpenAI API key not configured. Please set it in the extension options.",
      );
    }

    // Default prompt if none provided
    const customPrompt = `
Veuillez fournir un résumé TRÈS DÉTAILLÉ de cette transcription de vidéo YouTube en français.
Gardez les termes techniques en anglais s'ils sont habituellement utilisés en anglais.
Cette vidéo semble longue, donc soyez exhaustif et détaillé dans votre analyse.

## 0. Résumé brutal en une ligne
Une phrase qui résume honnêtement et directement le contenu principal.

## 1. Sujet Principal
Décrivez en détail de quoi traite la vidéo, le contexte, et l'angle d'approche utilisé (2-3 paragraphes).

## 2. Points Clés Détaillés
Listez 8-12 points importants avec des explications détaillées pour chacun:
- Point 1: [Explication détaillée]
- Point 2: [Explication détaillée]
- etc.

## 3. Insights et Leçons Approfondis
Développez en détail les insights les plus précieux, avec des exemples concrets et des applications pratiques (au moins 4-5 insights substantiels).

## 4. Citations et Aphorismes Marquants
Listez les meilleures citations, aphorismes ou phrases marquantes mentionnées.

## 5. Points à Retenir Essentiels
Liste exhaustive des éléments les plus importants à retenir, organisés par thème.

## 6. Mindmap Interactive
...

## 7. Conclusion Exhaustive
Synthèse complète reprenant tous les éléments majeurs, les implications, et les actions recommandées.

---
IMPORTANT: Soyez très détaillé, cette vidéo fait probablement plus d'une heure. Le résumé doit être proportionnel à la durée et richesse du contenu.
    `.trim();

    const prompt = `
${customPrompt}

Video Title: ${title}
Channel: ${channel || "Unknown"}

Transcript:
${transcript}
    `.trim();

    console.log("YouTube Summary: Making OpenAI API request");

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini", // More cost-effective model
        messages: [
          {
            role: "user",
            content: prompt,
          },
        ],
        max_tokens: 8000,
        temperature: 0.7,
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(
        `OpenAI API error: ${errorData.error?.message || response.statusText}`,
      );
    }

    const data = await response.json();
    const summary = data.choices[0]?.message?.content?.trim();

    if (!summary) {
      throw new Error("No summary generated by OpenAI API");
    }

    console.log("YouTube Summary: Summary generated successfully");
    return summary;
  } catch (error) {
    console.error("YouTube Summary: Error in generateAISummary:", error);
    throw error;
  }
}

// Handle extension icon click
chrome.action.onClicked.addListener((tab) => {
  if (tab.url.includes("youtube.com/watch")) {
    chrome.tabs.sendMessage(tab.id, { action: "triggerSummary" });
  } else {
    console.log("YouTube Summary: Not on a YouTube video page");
  }
});

// Handle keyboard shortcut
chrome.commands.onCommand.addListener((command) => {
  if (command === "trigger-summary") {
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      const tab = tabs[0];
      if (tab && tab.url.includes("youtube.com/watch")) {
        chrome.tabs.sendMessage(tab.id, { action: "triggerSummary" });
      } else {
        console.log("YouTube Summary: Not on a YouTube video page");
      }
    });
  }
});
