// background.js
console.log("YouTube Summary: Background script loaded");

chrome.runtime.onInstalled.addListener(() => {
  console.log("YouTube Summary: Extension installed");
});

// Handle messages from content script
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  console.log("YouTube Summary: Message received in background:", request);

  if (request.action === "generateSummary") {
    generateAISummary(request)
      .then((summary) => {
        sendResponse({ summary });
      })
      .catch((error) => {
        console.error("YouTube Summary: Error generating summary:", error);
        sendResponse({ error: error.message });
      });
    return true; // Keep message channel open for async response
  }

  return true;
});

// Generate AI summary using OpenAI API
async function generateAISummary({ transcript, title, channel, url }) {
  try {
    // Get API key from storage
    const result = await chrome.storage.sync.get([
      "openaiApiKey",
      "customPrompt",
    ]);
    const apiKey = result.openaiApiKey;

    if (!apiKey) {
      throw new Error(
        "OpenAI API key not configured. Please set it in the extension options.",
      );
    }

    // Default prompt if none provided
    const customPrompt = `
📺 Résumé EXHAUSTIF en français • Termes techniques → anglais • Vidéo ~1h+ = analyse proportionnelle

## 0. 🎯 Résumé brutal
→ Une phrase directe qui capture l'essence du contenu

## 1. 📋 Sujet Principal
* Contexte & problématique abordée
* Angle d'approche utilisé
* Positionnement dans son domaine

## 2. ⚡ Points Clés (8-12)
* Point → Explication détaillée + exemples concrets
* Point → Impact pratique + applications
* Point → Liens avec d'autres concepts
[Répéter pour chaque point essentiel]

## 3. 💡 Insights & Leçons
* 4-5 insights substantiels avec:
  - Exemples concrets
  - Applications pratiques
  - Pourquoi c'est important
  - Comment l'appliquer

## 4. 🗣️ Citations Marquantes
* Meilleures phrases/aphorismes
* Formulations percutantes
* Définitions clés

## 5. ✓ À Retenir (par thème)
* Thème 1: Points essentiels
* Thème 2: Éléments cruciaux
* Thème 3: Applications directes

## 6. 🔄 Actions Recommandées
* Première étape → résultat attendu
* Deuxième action → bénéfice
* Ressources à explorer

## 7. 🎬 Conclusion
Synthèse complète: éléments majeurs + implications + prochaines étapes

---
⚠️ DÉTAIL PROPORTIONNEL: Vidéo longue = résumé exhaustif (≠ superficiel)
    `.trim();

    const prompt = `
${customPrompt}

Video Title: ${title}
Channel: ${channel || "Unknown"}

Transcript:
${transcript}
    `.trim();

    console.log("YouTube Summary: Making OpenAI API request");

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini", // More cost-effective model
        messages: [
          {
            role: "user",
            content: prompt,
          },
        ],
        max_tokens: 8000,
        temperature: 0.7,
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(
        `OpenAI API error: ${errorData.error?.message || response.statusText}`,
      );
    }

    const data = await response.json();
    const summary = data.choices[0]?.message?.content?.trim();

    if (!summary) {
      throw new Error("No summary generated by OpenAI API");
    }

    console.log("YouTube Summary: Summary generated successfully");
    return summary;
  } catch (error) {
    console.error("YouTube Summary: Error in generateAISummary:", error);
    throw error;
  }
}

// Handle extension icon click
chrome.action.onClicked.addListener((tab) => {
  if (tab.url.includes("youtube.com/watch")) {
    chrome.tabs.sendMessage(tab.id, { action: "triggerSummary" });
  } else {
    console.log("YouTube Summary: Not on a YouTube video page");
  }
});

// Handle keyboard shortcut
chrome.commands.onCommand.addListener((command) => {
  if (command === "trigger-summary") {
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      const tab = tabs[0];
      if (tab && tab.url.includes("youtube.com/watch")) {
        chrome.tabs.sendMessage(tab.id, { action: "triggerSummary" });
      } else {
        console.log("YouTube Summary: Not on a YouTube video page");
      }
    });
  }
});
